org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2]
forge_version=43.5.2
forge_version_range=43.0.0
loader_version_range=43
mapping_channel=official
mapping_version=1.19.2

mod_id=steepmaterialconditionfix
mod_name=Steep Material Condition Fix
mod_license=GNU General Public License v3.0
mod_version=1.0.1
mod_group_id=io.github.jared6060.steepmaterialconditionfix
mod_authors=jared6060
mod_description=This mod provides a fix for MC-258859. It forces the steep surface condition to check if the current position is a steep face on all sides of a mountain, not just north and east.
